# Generated by Django 3.1.7 on 2022-05-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
